# This is a basic workflow to help you get started with Actions

name: Zadanie 1 dodatkowe 1 Maciej Rak

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-push-images:
    # The type of runner that the job will run on
    name: Budowana i publikacja obrazu w repozytorium
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check code
        uses: actions/checkout@v3

      # qemu setups
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Setup docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to github
        uses: docker/login-action@v1
        with:
          username: ${{secrets.NAME}}
          password: ${{secrets.PASSWD}}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          platforms: linux/arm64/v8,linux/amd64,linux/arm/v7
          file: ./Dockerfile
          push: true
          tags: maciejrak/zadanie1:zadanie_dodatkowe1
          cache-from: type=gha
          cache-to: type=gha,mode=max

